### PR TITLE
chore: bump ruby to 3.3.0

### PR DESCRIPTION
**Pull request by mhenrixon**
Figured I contribute back since I was building these anyway today. The resulting image is now used both on my machine and in production. Seems to be working fine but every PR feedback greatly appreciated.

### CODE REVIEW

**Review by dorianmariecom — APPROVED** [review]
Looks good to me, much simpler, have you tested the case of a wrong checksum?

**Comment by moritzheiber** [comment]
Hey folks, unfortunately, I cannot accept this PR since it does away with the implied versatility of the `Dockerfile`, which can be used to build pretty much any version available (if it's `>= 3.x`). What you are right about is the fact that the default needs adjusting (and the `README.md` needs updating) but e.g. version `3.3.0` is already [available as an image _right now_](https://github.com/moritzheiber/ruby-jemalloc-docker/pkgs/container/ruby-jemalloc/167787851?tag=3.3.0-slim) since they are automatically built from the output of [`ruby-version-checker`](https://github.com/moritzheiber/ruby-version-checker-rs) on [a continuous basis](https://github.com/moritzheiber/ruby-jemalloc-docker/blob/main/.github/workflows/build-push.yaml#L4). This process is [also explained in the README](https://github.com/moritzheiber/ruby-jemalloc-docker?tab=readme-ov-file#compiling-your-own-image).

Obviously, you're more than welcome to fork the repository and simplify the `Dockerfile` to your liking, but for the sake of keeping the intent alive I'll probably not accept the PR as-is.

In the meantime, I'll update the default and the README to match the status quo.

**Comment by mhenrixon** [comment]
> Hey folks, unfortunately, I cannot accept this PR since it does away with the implied versatility of the Dockerfile, which can be used to build pretty much any version available (if it's >= 3.x). 

Since these images are based on the official Ruby, they should match the default one in my opinion. I am only taking about the checksum handling btw. If you refer to the arg default value I can remove that. 

Anyway, it's your code, I already cloned it 🤣


@dorianmariefr yes, it fails like it does with the wrong checksum before.

**Comment by moritzheiber** [comment]
I'm closing this since the intention of the PR goes against the intention of the repository/image. Apologies, if that wasn't clear from the beginning and for the effort in vain.

PS: The images have been updated since and are available from the registry.

**Comment by mhenrixon** [comment]
It is okay, I'm not using this anymore anyway. I switched everything over to the default Dockerfile of the rails repo, which now easily enables both YJIT and jemalloc.

They also provide dev containers for new projects, so they might steal from there too to avoid unnecessary extra dependencies.

**Pull request closed without merging**
